sudo: required
services:
  - docker

before_install:
  - docker build -t avincze73/react-with-docker -f Dockerfile.dev .

script:
  - docker run avincze73/react-with-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "react-with-docker"
  env: "ReactWithDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-589253699265"
  bucket_path: "react-with-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
